apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8up-btl
resources:
  - namespace.yaml
  - rbac.yaml
  - pvc.yaml
  - deployment.yaml
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/name: k8up-btl
      app.kubernetes.io/part-of: k8up-btl
    includeSelectors: false
images:
  - name: ghcr.io/d-kholin/k8up-btl
    newTag: "1.1.0"